theme: jekyll-theme-cayman
title: Evaluate and Experiment in AWS
description: This blog lists some projects in AWS. I hope it helps in your cloud journey. Feel free to comment for feedback and suggestions
